import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProviders from "./context/ContextProviders";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ContextProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <Header />
          </header>
          <main className="min-h-screen mt-20 container mx-auto">{children}</main>
          <footer className="bg-muted/50 py-12">
            <div className="container mx-auto text-center text-gray-500 px-4">
              Footer
            </div>
          </footer>
        </body>
      </ContextProviders>
    </html>
  );
}
